### PR TITLE
fix: numpad +/- event.codes

### PR DESCRIPTION
**Pull request by sofusoe**
Fixed the event.code in Keymap dicts for numpad plus and minus, according to specification:

https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code/code_values

### CODE REVIEW

**Comment by unity-cla-assistant** [comment]
[CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/UnityRenderStreaming?pullRequest=353) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/UnityRenderStreaming?pullRequest=353) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.cds.internal.unity3d.com/check/Unity-Technologies/UnityRenderStreaming?pullRequest=353) it.</sub>

**Comment by sofusoe** [comment]
I get an error when signing the CLA. After clicking "Sign in with GitHub" i get a 403 permission denied.
As I can currently not sign the CLA the proper way, I will tell you here that I agree with all the terms of the Unity Individual Contributor License Agreement V1.0.

**Comment by karasusan** [comment]
Thanks for your contribution!

**Comment by karasusan** [comment]
All lines in files have been changed. It might be a change of line ending or a character-encode. Could you check them?

**Comment by karasusan** [comment]
I created another pull request to merge this PR from the user.
https://github.com/Unity-Technologies/UnityRenderStreaming/pull/383

**Pull request closed without merging**
