### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by vszoro**
fix: command error "pack": "pkg"

### CODE REVIEW

**Comment by unity-cla-assistant** [comment]
[CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/UnityRenderStreaming?pullRequest=833) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/UnityRenderStreaming?pullRequest=833) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.cds.internal.unity3d.com/check/Unity-Technologies/UnityRenderStreaming?pullRequest=833) it.</sub>

**Comment by karasusan** [comment]
Hi, thanks for contributing!
I tested your change but I got error below on Windows. Could you let me know if something wrong I tested. Thanks.

```
PS C:\UnityRenderStreaming\WebApp> npm run pack

> webserver@3.1.0 pack
> pkg

> pkg@5.8.0
> Error! Entry file/directory is expected
  Pass --help to see usage information
```

**Comment by karasusan** [comment]
@vszoro
Sorry but I am not sure what issue you are having. Could you tell me?

**Comment by karasusan** [comment]
@vszoro
I would like to close this PR if I don't have your reply. Thanks.

**Pull request closed without merging**
